/* Do not edit this file. */

import java.lang.Comparable;

public class Node<K extends Comparable<K>, V>
{
	public K key;
	public V value;
	
	public Node<K, V> parent;
	public Node<K, V> left;
	public Node<K, V> right;
	
	public Node(K key, V value, Node<K, V> parent, Node<K, V> left, Node<K, V> right)
	{
		this.key = key;
		this.value = value;
		
		this.parent = parent;
		this.left = left;
		this.right = right;
	}
}